# Generated by Django 4.0 on 2022-01-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_category',
            new_name='category',
        ),
    ]
