# Generated by Django 3.2.8 on 2021-11-24 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('dob', models.DateField(auto_now_add=True)),
                ('phone_no', models.CharField(max_length=10)),
                ('pic', models.ImageField(null=True, upload_to='blogs')),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('fb_address', models.CharField(default=' ', max_length=50)),
                ('insta_address', models.CharField(default=' ', max_length=50)),
                ('linkdin_id', models.CharField(default=' ', max_length=50)),
                ('github_id', models.CharField(default=' ', max_length=50)),
                ('twitter_id', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=250)),
                ('blog_image', models.ImageField(null=True, upload_to='blogs')),
                ('blog_description', models.TextField(max_length=1000)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Myeducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(default='Present')),
                ('level', models.CharField(max_length=20)),
                ('name_of_school_or_college', models.CharField(max_length=150)),
                ('school_or_college_address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Myexperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(default='Present')),
                ('post', models.CharField(max_length=100)),
                ('name_of_company', models.CharField(max_length=100)),
                ('address_of_company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Myprojects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=50)),
                ('language_used', models.CharField(max_length=20)),
                ('project_description', models.TextField(max_length=500)),
                ('project_image', models.ImageField(null=True, upload_to='blogs')),
            ],
        ),
        migrations.CreateModel(
            name='offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pic', models.ImageField(null=True, upload_to='blogs')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.blogs')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_category',
            field=models.ManyToManyField(related_name='categoreis', to='portfolio.Category'),
        ),
    ]
