# Generated by Django 3.2.8 on 2021-11-24 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='aboutme',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='dob',
            field=models.DateField(),
        ),
    ]
