# Generated by Django 3.2.8 on 2021-12-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20211124_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myskils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('skill_measure', models.IntegerField()),
            ],
        ),
    ]
