# Generated by Django 4.0 on 2022-01-03 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_myskils'),
    ]

    operations = [
        migrations.AddField(
            model_name='myskils',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myskils',
            name='pic',
            field=models.ImageField(null=True, upload_to='blogs'),
        ),
    ]
