# Generated by Django 4.0 on 2022-01-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_workingstyle_delete_myeducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadcv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cv', models.FileField(upload_to='portfolio')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='pic',
            field=models.ImageField(null=True, upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='myprojects',
            name='project_image',
            field=models.ImageField(null=True, upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='myskils',
            name='pic',
            field=models.ImageField(null=True, upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='pic',
            field=models.ImageField(null=True, upload_to='portfolio'),
        ),
    ]
